apiVersion: apps/v1
kind: Deployment
metadata:
  name: console
spec:
  selector:
    matchLabels:
      app: mcg-ms-console
  template:
    metadata:
      labels:
        app: mcg-ms-console
    spec:
      securityContext:
        runAsNonRoot: true
        allowPrivilegeEscalation: false
      containers:
        - name: mcg-ms-console
          image: mcg-ms-console:latest
          resources:
            limits:
              cpu: "100m"
              memory: "512Mi"
            requests:
              cpu: "100m"
              memory: "512Mi"
          ports:
            - containerPort: 9002
              protocol: TCP
          livenessProbe:
            initialDelaySeconds: 15
            periodSeconds: 20
            tcpSocket:
              port: 9002
          readinessProbe:
            initialDelaySeconds: 5
            periodSeconds: 10
            tcpSocket:
              port: 9002
          volumeMounts:
            - name: mcg-ms-console-serving-cert
              mountPath: /var/serving-cert
              readOnly: true
      tolerations:
      - effect: NoSchedule
        key: node.ocs.openshift.io/storage
        operator: Equal
        value: "true"
      volumes:
        - name: mcg-ms-console-serving-cert
          secret:
            secretName: mcg-ms-console-serving-cert
