apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  creationTimestamp: null
  name: mcg-osd-deployer-dedicated-admin-df
rules:
- apiGroups:
  - noobaa.io
  resources:
  - '*'
  verbs:
  - create
  - delete
  - get
  - list
  - watch
  - update
  - patch
