kind: ConfigMap
apiVersion: v1
metadata:
  name: addon-env
  namespace: redhat-data-federation
data:
  SOP_ENDPOINT: test.url
  ALERT_SMTP_FROM_ADDR: test@redhat.com
  NOOBAA_DB_IMAGE: registry.redhat.io/rhel8/postgresql-12@sha256:be7212e938d1ef314a75aca070c28b6433cd0346704d0d3523c8ef403ff0c69e
  ADDON_VARIANT: dev
  NOOBAA_CORE_IMAGE: registry.redhat.io/odf4/mcg-core-rhel8@sha256:4ff2d65ea16dd1026fe278a0f8ca920f300dfcee205b4b8ede0ab28be1aa43a6
  OPERATOR_CONDITION_NAME: mcg-osd-deployer.v1.0.0
  ADDON_NAME: mcg-osd
  RHOBS_ENDPOINT: https://observatorium-mst.api.stage.openshift.com/receive
  RH_SSO_TOKEN_ENDPOINT: https://sso.redhat.com/auth/token
  ADDON_ENVIRONMENT: stage
