kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: dedicated-admin-df
rules:
  - verbs:
      - create
      - delete
      - get
      - list
      - watch
      - update
      - patch
    apiGroups:
      - noobaa.io
    resources:
      - '*'
