# permissions for end users to view managedmcgs.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: managedmcg-viewer-role
rules:
- apiGroups:
  - mcg.openshift.io
  resources:
  - managedmcg
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - mcg.openshift.io
  resources:
  - managedmcg/status
  verbs:
  - get
