apiVersion: v1
kind: Namespace
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","kind":"Namespace","metadata":{"annotations":{},"labels":{"hive.openshift.io/managed":"true","managed.openshift.io/storage-pv-quota-exempt":"true"},"name":"openshift-storage","namespace":""}}
    openshift.io/sa.scc.mcs: s0:c30,c20
    openshift.io/sa.scc.supplemental-groups: 1000910000/10000
    openshift.io/sa.scc.uid-range: 1000910000/10000
  creationTimestamp: "2022-01-25T13:10:28Z"
  deletionTimestamp: "2022-01-25T13:45:38Z"
  labels:
    hive.openshift.io/managed: "true"
    kubernetes.io/metadata.name: openshift-storage
    managed.openshift.io/storage-pv-quota-exempt: "true"
  managedFields:
  - apiVersion: v1
    fieldsType: FieldsV1
    fieldsV1:
      f:metadata:
        f:annotations:
          f:openshift.io/sa.scc.mcs: {}
          f:openshift.io/sa.scc.supplemental-groups: {}
          f:openshift.io/sa.scc.uid-range: {}
    manager: cluster-policy-controller
    operation: Update
    time: "2022-01-25T13:10:28Z"
  - apiVersion: v1
    fieldsType: FieldsV1
    fieldsV1:
      f:metadata:
        f:annotations:
          .: {}
          f:kubectl.kubernetes.io/last-applied-configuration: {}
        f:labels:
          .: {}
          f:hive.openshift.io/managed: {}
          f:kubernetes.io/metadata.name: {}
          f:managed.openshift.io/storage-pv-quota-exempt: {}
    manager: oc
    operation: Update
    time: "2022-01-25T13:10:28Z"
  - apiVersion: v1
    fieldsType: FieldsV1
    fieldsV1:
      f:status:
        f:conditions:
          .: {}
          k:{"type":"NamespaceContentRemaining"}:
            .: {}
            f:lastTransitionTime: {}
            f:message: {}
            f:reason: {}
            f:status: {}
            f:type: {}
          k:{"type":"NamespaceDeletionContentFailure"}:
            .: {}
            f:lastTransitionTime: {}
            f:message: {}
            f:reason: {}
            f:status: {}
            f:type: {}
          k:{"type":"NamespaceDeletionDiscoveryFailure"}:
            .: {}
            f:lastTransitionTime: {}
            f:message: {}
            f:reason: {}
            f:status: {}
            f:type: {}
          k:{"type":"NamespaceDeletionGroupVersionParsingFailure"}:
            .: {}
            f:lastTransitionTime: {}
            f:message: {}
            f:reason: {}
            f:status: {}
            f:type: {}
          k:{"type":"NamespaceFinalizersRemaining"}:
            .: {}
            f:lastTransitionTime: {}
            f:message: {}
            f:reason: {}
            f:status: {}
            f:type: {}
    manager: kube-controller-manager
    operation: Update
    subresource: status
    time: "2022-01-25T13:45:56Z"
  name: openshift-storage
  resourceVersion: "1080903"
  uid: c18ac5eb-139e-4726-ad29-9ef964132057
spec:
  finalizers:
status:
  conditions:
  - lastTransitionTime: "2022-01-25T13:45:56Z"
    message: All resources successfully discovered
    reason: ResourcesDiscovered
    status: "False"
    type: NamespaceDeletionDiscoveryFailure
  - lastTransitionTime: "2022-01-25T13:45:56Z"
    message: All legacy kube types successfully parsed
    reason: ParsedGroupVersions
    status: "False"
    type: NamespaceDeletionGroupVersionParsingFailure
  - lastTransitionTime: "2022-01-25T13:46:21Z"
    message: All content successfully deleted, may be waiting on finalization
    reason: ContentDeleted
    status: "False"
    type: NamespaceDeletionContentFailure
  - lastTransitionTime: "2022-01-25T13:45:56Z"
    message: 'Some resources are remaining: cephblockpools.ceph.rook.io has 1 resource
      instances, cephclusters.ceph.rook.io has 1 resource instances, cephfilesystems.ceph.rook.io
      has 1 resource instances, managedocs.ocs.openshift.io has 1 resource instances,
      storageclusters.ocs.openshift.io has 1 resource instances, storagesystems.odf.openshift.io
      has 1 resource instances'
    reason: SomeResourcesRemain
    status: "True"
    type: NamespaceContentRemaining
  - lastTransitionTime: "2022-01-25T13:45:56Z"
    message: 'Some content in the namespace has finalizers remaining: cephblockpool.ceph.rook.io
      in 1 resource instances, cephcluster.ceph.rook.io in 1 resource instances, cephfilesystem.ceph.rook.io
      in 1 resource instances, managedocs.ocs.openshift.io in 1 resource instances,
      storagecluster.ocs.openshift.io in 1 resource instances, storagesystem.odf.openshift.io
      in 1 resource instances'
    reason: SomeFinalizersRemain
    status: "True"
    type: NamespaceFinalizersRemaining
  phase: Terminating
