kind: Secret
apiVersion: v1
metadata:
  name: addon-ocs-converged-parameters
  namespace: openshift-storage
stringData:
  size: "1"
  notification-email-0: "napaul@redhat.com"
  notification-email-1: "napaul@redhat.com"
  notification-email-2: "napaul@redhat.com"
  enable-mcg: "true"
type: Opaque
---

kind: Secret
apiVersion: v1
metadata:
  name: ocs-converged-deadmanssnitch
  namespace: openshift-storage
stringData:
  SNITCH_URL: https://nosnch.in/4a029adb4c
type: Opaque
---

kind: Secret
apiVersion: v1
metadata:
  name: ocs-converged-pagerduty
  namespace: openshift-storage
stringData:
  PAGERDUTY_KEY: testKey
type: Opaque
---
apiVersion: v1
data:
  host: c210cC5zZW5kZ3JpZC5uZXQ=
  password: dGVzdC1wYXNzd29yZAo=
  port: NTg3
  tls: dHJ1ZQ==
  username: YXBpa2V5
kind: Secret
metadata:
  name: ocs-converged-smtp
  namespace: openshift-storage
type: Opaque
